// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {collector} from '../models';

export function GetSystemSnapshot():Promise<collector.SystemSnapshot>;

export function KillProcess(arg1:number):Promise<void>;
